import type { NextPage } from 'next'
import Head from 'next/head'
import Amplify from "@aws-amplify/core";
import { CognitoHostedUIIdentityProvider } from '@aws-amplify/auth';
import App from '../component/aws-cognito-login/App'
import React, { useEffect, useState } from 'react';

import awsExports from "../src/aws-exports";


import awsconfig from '../src/aws-exports'
import Checkuser from './Checkuser';
Amplify.configure({ ...awsExports, ssr: true });


const Home: NextPage = () => {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<b><h3 >Welcome To PKDRFINANCE</h3></b>
     <App />


    
    </div>
  )
}

export default Home
